import {
  homeView,
  overview,
  incomesView,
  expensesView,
  assetsView,
  debtsView,
  taxView,
  triggersView,
  transactionsView,
  reportView,
  optimizerView,
  planningView,
  settingsView,
} from "../localization/stringConstants";

export const allViews = [
  homeView,
  overview,
  incomesView,
  expensesView,
  assetsView,
  debtsView,
  taxView,
  triggersView,
  transactionsView,
  reportView,
  optimizerView,
  planningView,
  settingsView,
];
